Repository fabricadesoftware-ifc/fabricaNode_FrontEnd, pull requests merged in 2024-07, with the labels that each got.

#34 Add Home Page
  dev-dist/sw.js
  src/assets/grafo.png
  src/assets/logo-fabrica-de-software.png
  src/assets/logo-github.png
  src/assets/logo-instagram.png
  src/assets/logo-linked-in.png
  src/assets/logo-twiter.png
  src/components/footer/DeafaultFooter.vue
  src/components/footer/contact/FabricaContact.vue
  src/components/footer/links/FastLinks.vue
  src/components/footer/links/LinksFabrica.vue
  src/components/footer/links/LinksHeader.vue
  src/components/footer/links/imagesLinks.vue
  src/components/footer/logo/LogoFabrica.vue
  src/components/footer/titles/FooterTitles.vue
  src/components/header/DesktopHeader.vue
  src/components/header/logo/TextLogo.vue
  src/components/header/titles/ListTitles.vue
  src/components/home/DefaultHome.vue
  src/components/home/button/ButtonGraph.vue
  src/components/home/image/GraphImage.vue
  src/components/home/titles/description/DescriptionTitle.vue
  src/components/home/titles/title/TitlesHome.vue
  src/components/index.ts
  src/pages/FavoriteView.vue
  src/pages/GraphView.vue
  src/pages/HomeView.vue
  src/pages/LoginView.vue
  src/router/index.ts
  src/stores/template/template.ts
Labels: enhancement, good first issue

#35 Add node label
  dev-dist/sw.js
  mock/articles/articles.ts
  package-lock.json
  package.json
  src/assets/main.css
  src/components/graph/label/DefaultLabel.vue
  src/components/graph/label/NodeLabel.vue
  src/components/graph/label/author/AuthorName.vue
  src/components/graph/label/category/CategoryLabel.vue
  src/components/graph/label/name/ArticleName.vue
  src/components/icons/index.ts
  src/components/index.ts
Labels: enhancement, good first issue

#36 Add children layouts
  src/components/home/DefaultHome.vue
  src/layouts/BlankLayout.vue
  src/layouts/DefaultLayout.vue
  src/layouts/GraphLayout.vue
  src/pages/AboutView.vue
  src/pages/ArticleView.vue
  src/pages/AuthorView.vue
  src/pages/FavoriteView.vue
  src/pages/GraphView.vue
  src/pages/HomeView.vue
  src/pages/ProfileView.vue
  src/router/index.ts
Labels: enhancement, good first issue

#38 Add DevView
  dev-dist/sw.js
  src/assets/construction.jpg
  src/pages/DevView.vue
  src/router/index.ts
Labels: enhancement, good first issue

#41 Add vue3-toastify
  dev-dist/sw.js
  package-lock.json
  package.json
  src/plugins/index.ts
  src/plugins/toast/toastify.ts
Labels: documentation, enhancement, good first issue

#45 Add project logo
  index.html
  public/apple-touch-icon.png
  public/favicon.ico
  public/logo.png
  public/pwa-192x192.png
  public/pwa-512x512.png
Labels: enhancement, good first issue

#46 Mock rewriting and updating pull files
  dev-dist/sw.js
  mock/authors/authors.ts
  mock/categories/categories.ts
  mock/index.ts
  mock/keywords/keywords.ts
  mock/publications/publications.ts
  src/components/graph/label/author/AuthorName.vue
  src/components/graph/label/category/CategoryLabel.vue
  src/composables/graph/setGraph.ts
  src/interfaces/article/article.ts
  src/interfaces/author/author.ts
  src/interfaces/category/category.ts
  src/interfaces/index.ts
  src/interfaces/keyword/keyword.ts
  src/interfaces/publication/publication.ts
  src/services/author/author.ts
  src/services/category/category.ts
  src/services/index.ts
  src/services/keyword/keyword.ts
  src/services/publication/publication.ts
  src/stores/index.ts
  src/stores/publication/publication.ts
Labels: bug, enhancement

#47 Refactore Header, Footer and Home styles
  dev-dist/sw.js
  src/assets/grafo.png
  src/assets/logo-fabrica-de-software.png
  src/assets/logo.png
  src/components/footer/DeafaultFooter.vue
  src/components/header/DesktopHeader.vue
  src/components/header/MobileHeader.vue
  src/components/header/buttons/LoginButton.vue
  src/components/header/logo/TextLogo.vue
  src/components/header/titles/ListTitles.vue
  src/components/home/DefaultHome.vue
  src/components/home/button/ButtonGraph.vue
  src/components/home/image/GraphImage.vue
  src/components/home/titles/description/DescriptionTitle.vue
  src/components/home/titles/title/TitlesHome.vue
  src/components/icons/index.ts
  src/composables/index.ts
  src/composables/screen/navbar.ts
  src/pages/GraphView.vue
  src/router/index.ts
  src/stores/template/template.ts
Labels: enhancement, good first issue

#48 Add loged header
  src/assets/user.jpg
  src/components/header/DesktopHeader.vue
  src/components/header/profile/UserProfile.vue
  src/components/header/profile/photo/UserPhoto.vue
  src/components/index.ts
Labels: enhancement, good first issue

#49 Add props in node label component
  src/components/graph/label/DefaultLabel.vue
  src/components/graph/label/author/AuthorName.vue
  src/components/graph/label/category/CategoryLabel.vue
  src/components/graph/label/name/ArticleName.vue
Labels: enhancement, good first issue
